### ISSUE TITLE
Python sox behavior

### ISSUE THREAD

**Issue by f4iey** [f4iey/taglio#1]
Sometimes, the RAW output file is kind of corrupted:
1. the file is shorter
2. the frequency is higher
Just lik we *squeezed the original file*
However, calling the program `/bin/sox TEST.wav -t raw -b 16 -c 1 -r 44100 TEST.RAW` works perfectly...

**Comment by jramboz** [comment]
If you want an alternate method, I wrote a function for converting wav to raw using [pydub](https://pydub.com/).

https://github.com/jramboz/tintalle/blob/main/sound.py

I haven't thoroughly tested it yet, but so far the results are good. Best of all, it doesn't need any external program. (pydub does use external ffmpeg or libav for many filetypes, but it doesn't need it for wav or raw.)
