### ISSUE TITLE
Suggestion: check for Anima NXT before flashing FW

### ISSUE THREAD

**Issue by jramboz** [f4iey/taglio#2]
For firmware flashing, I suggest checking if the Anima is a NXT and that the FW file is compatible. I haven't tried uploading a non-NXT file to an NXT, but I imagine nothing good will happen! Maybe you can protect someone from bricking their very expensive new Anima. 

The easiest way to check is to get the FW version from the Anima. NXT FW versions start with `"NXT_"`.

**Comment by f4iey** [comment]
Did you manage to find where the NXT binaries are?
I don't think that is necessary: `tytools` was not made for STM32 boards and seems to prevent any other hex files that is not compatible with Teensy hardware from flashing as it does not recognize the header.

**Comment by jramboz** [comment]
As far as I know, the NXT FW hasn't been posted anywhere yet. I'm still waiting... 

Good to know `tycmd` will reject it. I hadn't been brave enough to try yet!
